### ISSUE TITLE
http://www.ligatus.org.uk/lcd URI appearing too frequently

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#1]
I am noticing that several records from the Bodleian datasets have this URI: "http://www.ligatus.org.uk/lcd" appearing frequently. It looks like the UUID component of the URI is not being attached to the rest. For example in [8voS188Art.rdf](https://github.com/linked-conservation-data/board-pilot-data/blob/main/bod/individual-records/8voS188Art.rdf) and [6062.rdf](https://github.com/linked-conservation-data/board-pilot-data/blob/main/bod/individual-records/6062.rdf)

**Comment by acampagnolo** [comment]
I am not sure what causes this, but I think I've fixed it: it occurred when I was doing a batch transformation as opposed to do one file at the time. Hopefully, when I manage to put together the XProc pipeline, this won't occur. I'll keep an eye on this.

**Comment by acampagnolo** [comment]
This should be fixed now, avoiding batch transformations in Oxygen
