### ISSUE TITLE
Check that all URIs are http

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#10]
I came up with a problem when running SPARQL queries on the datasets where there was a mismatch of URIs because of `https` and `http`. I think the problem was only on the vocabularies which I have updated to `http` now. Can you check that the datasets are using vocabulary URIs with `http` throughout?

**Comment by ryunleeuu** [comment]
fixed

**Comment by acampagnolo** [comment]
fixed
