### ISSUE TITLE
Boards not linked to any events in LC data

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#13]
It appears that the boards in the LC records are not linked to any modification event and therefore there are no techniques or dates associated with them. I have checked records 2028 and 1466_027 - models below:
![1466_027 gv](https://user-images.githubusercontent.com/7868713/101637402-9fd98b00-3a24-11eb-8db9-698552a37e10.png)
![2028 gv](https://user-images.githubusercontent.com/7868713/101637420-a7009900-3a24-11eb-80f8-6ef68e399f67.png)

**Comment by acampagnolo** [comment]
This was due to the selection of records. I went through the data and selected a different set of records with more targeted data. I'll regenerate the RDFs once I have finished updating the scripts.

**Comment by acampagnolo** [comment]
In generating the new dataset, I've encountered 4 terms that weren't in the vocabulary. They are added and highlighted in green in the spreadsheet of inferred terms: https://docs.google.com/spreadsheets/d/1eDVvIKZGwt1h8RoLaC5rED_3P0ZpYh9OB025BhC4vRU/edit#gid=0

**Comment by natuk** [comment]
Hm, I have looked at a few records and again I cannot find any modification events linked to boards. I checked: 3929, 2687, 2561, 2028.

**Comment by acampagnolo** [comment]
you managed to pick items without board info! Try 1697, 2247, 2473, 2474, 2605
See this list for possible candidates
[LOC_FileSelection_20201210.xlsx](https://github.com/linked-conservation-data/board-pilot-data/files/5717543/LOC_FileSelection_20201210.xlsx)

**Comment by natuk** [comment]
No, I am afraid that in all of these records, the boards are not connected to any modification events. See for example 1697:
![1697 gv](https://user-images.githubusercontent.com/7868713/102695577-2ad63480-4220-11eb-8dc3-bb44b4fd8140.png)
Also this example shows double modification events as noted at #19 - possibly related?

**Comment by acampagnolo** [comment]
Caught an xpath issue. Regenerated the RDFs (this only applied to the LoC data). The double modification is not a problem if it has a technique, the bug was duplicating one instance without adding the technique.

**Comment by natuk** [comment]
Thank you - these look good now.
