### ISSUE TITLE
Entity labels are too long

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#14]
In some entities from the SL records the names are too long, for example:
![Screenshot from 2020-12-09 13-57-46](https://user-images.githubusercontent.com/7868713/101638968-a7019880-3a26-11eb-8cd0-e37eb97bafac.png)
Can these be made shorter and move the longer text in a string with `P3_has_note`?

**Comment by ryunleeuu** [comment]
Fixed these in the "Conservation of ..." event labels, but this is caused by the long catalog titles of many of our books. I haven't edited the labels for the E35_Title entities. Do you need me to? Can put full title into a P3_has_note

**Comment by natuk** [comment]
Hm, I see. No I do not think we should change the titles but it is useful to truncate the event labels. I will also modify my crmviz script to shorten these titles if they are too long.

**Comment by ryunleeuu** [comment]
@natuk I can easily rewrite the label generators for event labels, but what string length is a good limit for you to truncate at? 50 characters?

**Comment by ryunleeuu** [comment]
Fixed. Truncating labels at 50 characters in mapping as shorter will not have much meaning. Full event titles mapped as P3_has_note
