### ISSUE TITLE
E11_Modification does not have P111_added

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#15]
SL records include `E11_Modification` events which appear to have `P111_added` properties but this is not a valid CRM statement. The `E11_Modification` events need to be Part Addition events instead. See for example from record 4447_NewPracticalNavigator1800:
![Screenshot from 2020-12-09 14-08-04](https://user-images.githubusercontent.com/7868713/101640595-9a7e3f80-3a28-11eb-9e5f-268b8b05ab84.png)

**Comment by ryunleeuu** [comment]
fixed
