### ISSUE TITLE
Board modification events do not connect with Time-span

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#16]
In order to be able to sort board attachment techniques chronologically, we need the events affecting boards to link to broader events (of overall conservation or similar) which have a time-span attached. This could be done with `P9_consists_of`. Again looking at the 4447_NewPracticalNavigator1800 example the board modification event does not seem to be part of the treatment steps and also the treatment steps do not have a time-span either.

**Comment by ryunleeuu** [comment]
Fixed
