### ISSUE TITLE
Group time-spans by decade

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#17]
Following discussion at the meeting yesterday, can we use the `P86_falls_within` property to link the `E52_Time-Span` nodes to new time spans with begin and end of the decades it falls in?

**Comment by ryunleeuu** [comment]
Which domain do you want the time-span linked to? The entire "Conservation of" E7_Event?

**Comment by natuk** [comment]
Yes, I think @acampagnolo has linked the time-span to the broadest conservation event "E7 Activity" or I think "E11 Modification".

**Comment by ryunleeuu** [comment]
Fixed

**Comment by natuk** [comment]
I hope I have not confused both of you with this one. It needs to be like this:
"general treatment event" - has time span - "general treatment event time-span"
"general treatment event time-span" - falls within - "decade time-span"
"general treatment event time-span" - end of the end - <date on record>
"decade time-span" - begin of the begin - <start of decade>
"decade time-span" - end of the end - <end of decade>
So then I can filter based on the decade dates as opposed to the treatment record dates. Does this make sense?

**Comment by acampagnolo** [comment]
I guess we also need consistent UUIDs for each decade timeSpan?
i.e. one UUID for each instance of the 2010 decade? I can do this for my datasets, but should these be consistent across all datsets?

**Comment by acampagnolo** [comment]
fixed

**Comment by natuk** [comment]
@acampagnolo: In the loc and bod datasets the falls within property is misspelled as "P86_falls_whitin". I have corrected this in the aggregated files for ResearchSpace, but the XSLT scripts need fixing as well.

**Comment by acampagnolo** [comment]
fixed
