### ISSUE TITLE
Multiple modification events for boards

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#19]
The TNA records look great. I noticed that there are 3 modification events for each board (and other components) in the file:
[WO69-905](https://github.com/linked-conservation-data/board-pilot-data/blob/main/tna/individual-records/WO69-905.rdf). This is not semantically wrong, but I was wondering if it reflects the actual record.
![WO69-905 gv](https://user-images.githubusercontent.com/7868713/102660952-d8d7d500-4173-11eb-95ba-0071f2b53b0e.png)

**Comment by acampagnolo** [comment]
There was a bug that output an additional modification without technique. I've regenerated the RDFs.
Fixed.

**Comment by natuk** [comment]
I have just pulled the recent files. I am afraid in this example they appear as having two modification events now. See here:
![WO69-905 gv](https://user-images.githubusercontent.com/7868713/102695318-666fff00-421e-11eb-9b7d-88144bf78c7a.png)
I hope this is not a problem with crm-viz

**Comment by natuk** [comment]
Looks good now - thank you.
