### ISSUE TITLE
Some Bodleian records do not validate

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#2]
Validation errors received with the following:
* [GPamph1670.rdf](https://github.com/linked-conservation-data/board-pilot-data/blob/main/bod/individual-records/GPamph1670.rdf)
* [MSeMus65.rdf](https://github.com/linked-conservation-data/board-pilot-data/blob/main/bod/individual-records/MSeMus65.rdf)
* [MsBOM187.rdf](https://github.com/linked-conservation-data/board-pilot-data/blob/main/bod/individual-records/MsBOM187.rdf)

Also this appears as an incomplete file: [C822Line](https://github.com/linked-conservation-data/board-pilot-data/blob/main/bod/individual-records/C822Line)

**Comment by acampagnolo** [comment]
Fixed GPamph1670.rdf, MSeMus65.rdf, and C822Line.
I could not identify an issue with MsBOM187.rdf, can you point to the problem in this file?

**Comment by natuk** [comment]
MsBOM187.rdf appears heavily truncated... Maybe it was a transfer problem.

**Comment by acampagnolo** [comment]
This should be fixed now: there were some issues with dates in the format of 17th-18th century. Also, the batch transformation in Oxygen might have broken things.
