### ISSUE TITLE
Time-span of main conservation event does not have attached date

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#21]
TNA data is missing the `crm:P82b_end_of_the_end` property between the time-span of the main conservation event and the date of the treatment. This is needed in addition to the decade it falls within in order to plot the complete dataset in a timeline.

**Comment by acampagnolo** [comment]
Unless I misunderstood the issue, I see it in my records. 
<img width="633" alt="2020-12-23_16h59_17" src="https://user-images.githubusercontent.com/1773481/103015265-62a2ec00-4540-11eb-9697-c02b49f12233.png">

**Comment by natuk** [comment]
I do not mean the decade P82a and P82b. I mean the time-span of the event, which needs the P82b.
![103015265-62a2ec00-4540-11eb-9697-c02b49f12233](https://user-images.githubusercontent.com/7868713/103019385-a268d400-453e-11eb-91b4-5222937a74e7.png)

**Comment by acampagnolo** [comment]
Got it. Fixed and new RDFs pushed to github.

**Comment by natuk** [comment]
Yes, TNA appeared in the chart now. Thank you.
