### ISSUE TITLE
Wrong range for P126

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#23]
In some cases (for example Bod MSeMus65) the range of `P126_employed` appears as `S10_Material_Substantial`, but it can only be `E57_Material`. This is a problem when querying for materials over time in board modification events.

**Comment by acampagnolo** [comment]
That was to map solutions, what do you suggest doing? P16_used_specific_object?

**Comment by natuk** [comment]
Yes, maybe this is better, if we do not consider the solution as a type.

**Comment by acampagnolo** [comment]
Ok, corrected. This only applied to the Bodleain data. Pushed new RDFs
