### ISSUE TITLE
Condition States and their Types have the same URI

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#24]
I have run the transformation on 3M on the SUL data and visualised one with CRMVIZ. It looks as if the UIRs for the instances of Condition State are the same as their types. Or rather that the P2_has_type from the Condition State instance points to itself. See attached.
![Screenshot from 2020-12-30 12-28-55](https://user-images.githubusercontent.com/7868713/103351277-a3e45000-4a9a-11eb-824a-58e77cb2d8e5.png)

**Comment by ryunleeuu** [comment]
I think this is fixed. The problem seemed to be that the mapping for Condition_State was using an intermediate (e.g. has_condition , Condition_State , has_type > Type) that for some reason was rendering the Condition_State and Type URIs as the same even though the Generators were pointing to different nodes. Revised the mapping with separate maps for each condition state node and uploaded new version of .trig dataset.
