### ISSUE TITLE
Board techniques not linked

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#25]
It appears that techniques are only mentioned in relation to the part addition events which are not linked to boards. Are there no techniques directly connected to board events?

**Comment by ryunleeuu** [comment]
Sorry, but I'm not sure how this can help with the differences in the models vs. querying, but I've traced from boards to specific reattachment techniques and have a little explanation of my model. 

Our data includes only three specific board reattachment techniques-- "paper hinge" (http://w3id.org/sul-vocab/e8173325-216d-49b9-a645-81ea4f49e142), "rebacking" (http://w3id.org/sul-vocab/d4eb8b9f-ded5-4194-a890-439f30adffbe), and "hinge extensions" (http://w3id.org/sul-vocab/b2540530-85f9-4f75-84ea-f115ab4932ec). 

They way they "connect" to boards is that 
a board 
: <http://www.cidoc-crm.org/cidoc-crm/P111i_was_added_by> 
: <http://www.cidoc-crm.org/cidoc-crm/E79_Part_Addition> (with label "Component Application") 
: that <http://www.cidoc-crm.org/cidoc-crm/P33_used_specific_technique> 
: whichever <http://www.cidoc-crm.org/cidoc-crm/E29_Design_or_Procedure> was inferred from our report.

**Comment by natuk** [comment]
Thank you for explaining this. I think the main problem is that you are using `P33_used_specific_technique`. It should be `P32_used_general_technique`, because all of the three types you mention are vocabulary concepts, i.e. `E55 Type` and not `E29 Design or Procedure` which is meant to describe things which cannot be described by a type. If this is changed then I think I can modify the techniques query to pick up Part Addition as well as a child class of Modification.

**Comment by ryunleeuu** [comment]
Okay--I've removed any use of P33_used_specific_technique, so now all techniques follow an almost identical path as described above, except that they are connected as used_general_technique > E55_Type --uploading new dataset 20210115
