### ISSUE TITLE
Condition Assessments have too many links

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#26]
It looks like every condition assessment event links to all conditions and all components in the dataset. For example see:

https://lcd.researchspace.org/resource/?uri=http%3A%2F%2Fw3id.org%2Fsul-data%2Fb9222d6b-946e-4b1d-9ed7-d56780b040ad

and 

https://lcd.researchspace.org/resource/?uri=http%3A%2F%2Fw3id.org%2Fsul-data%2F728d147b-466a-419e-9f51-0f38e11d277b

They both indicate the same condition state of "loose":

https://lcd.researchspace.org/resource/?uri=http%3A%2F%2Fw3id.org%2Fsul-data%2F0109c419-0857-47b6-a1d7-8abd0f095926

**Comment by ryunleeuu** [comment]
Should be fixed now. Uploaded updated dataset sul-data-2021-01-08.trig. I missed the // xpath references here when updating in December--Sorry about that.

**Comment by natuk** [comment]
Ah OK, thank you Ryan. If you are transforming from within 3M, then the resulting trig file is not well-formed. You could try using this command line utility: https://github.com/isl/x3ml/releases for the transformation or send me the XML file and the 3M zip file to transform locally over here.

**Comment by ryunleeuu** [comment]
Oh--I'm using the Java-based 3M utility (with GUI) to transform rather than the command line utility. I've used both, and it seems they both function in the same way. Are the .trig datasets I've been uploading not well-formed?

**Comment by natuk** [comment]
Yes, the online version does the bulk of the job but it does not serialise the result in full. The files do not validate. Will follow up on email.

**Comment by natuk** [comment]
My bad, they validate OK and the issue is resolved now.
