### ISSUE TITLE
E22 URI does not match version of CRM used

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#3]
We were keen to adopt the `E22_Human-Made_Object` as a label and URI in the models used. Given that the CRM version 7.1 is not officially released yet and ResearchSpace is making use of the previous version, it would be useful to revert to `E22_Man-Made_Object` so that ResearchSpace picks up the right entity template for these records.

**Comment by acampagnolo** [comment]
Fixed

**Comment by acampagnolo** [comment]
Did the same for E25_Human-Made_Feature

**Comment by ryunleeuu** [comment]
I modeled on 6.2.1 since that's default in 3M, so should all be okay in SUL data

**Comment by natuk** [comment]
Yes, thank you.
