### ISSUE TITLE
E55 Type used for books

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#4]
We should use [codices (bound manuscripts)](http://vocab.getty.edu/aat/300224200) from the AAT for typing books in the datasets and not the LoB entry [codex-form books](http://w3id.org/lob/concept/4886). In general we opt for AAT if the local dataset does not provide its own type, and then drop to LoB if AAT does not cover the term.
Also the Stanford dataset seems not to include types for books, so these cannot be retrieved.

**Comment by acampagnolo** [comment]
Fixed

**Comment by ryunleeuu** [comment]
We don't capture this as an explicit data point in itself but rather only possibly in free text, so it won't be available as it is in the other datasets.

**Comment by natuk** [comment]
Can we add this retrospectively to the dataset? It could be a constant statement in 3M. It is not critical if not.

**Comment by kristen-stjohn** [comment]
Why would codex be a better choice than [book](http://vocab.getty.edu/aat/300028051)?
As far as I recall none or almost none of our pilot data are manuscripts.

**Comment by ryunleeuu** [comment]
I'm willing to add AAT for "books" or initial LoB for "codex-form books" since they'll suit our objects--will AAT for "books" shared by Kristen work?

**Comment by natuk** [comment]
Absolutely, I think this makes more sense. @acampagnolo can you also update the transformation for Bod and LoC?

**Comment by ryunleeuu** [comment]
fixed so all our objects have type <http://vocab.getty.edu/aat/300028051>

**Comment by acampagnolo** [comment]
changed to "books", but the link to the AAT is now on the vocabulary side and not in the RDFs

**Comment by natuk** [comment]
OK, so sul data have a direct link to AAT for book type whereas loc, bod and tna have an indirect link. I can create a union query to catch both cases.
