### ISSUE TITLE
P82b_end_of_the_end does not link to xsd:date

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#7]
It appears that in sul-data the range of P82b_end_of_the_end is another node and not a xsd:date. For example we currently have:

Field | Value
-- | --
label | "2002-06-26T00:00:00" - en                                                   "Latest Date" - en                                                   "Text Documentation Date" - en
type | dateTimeTime-Span
end of the end | https://w3id.org/sul-data/5e059746-6b8f-48b9-bd40-c96902bb7fa3
has type | completion date

whereas we should only have this as a plain xsd:date.

**Comment by ryunleeuu** [comment]
Believe this is fixed, but let me know if my correction is wrong.

**Comment by ryunleeuu** [comment]
Deploying same fix for 82a_begin_of_the_begin

**Comment by natuk** [comment]
Yes, I think this should be OK now.
