### ISSUE TITLE
Replace all types with local vocabulary terms

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#8]
Some types in the three datasets use URIs from Language of Bindings or AAT directly. These need to be replaced by local vocabulary URIs for the matching terms, to avoid complexity with the SPARQL query. For example this record: https://lcd.researchspace.org/resource/?uri=http%3A%2F%2Fwww.ligatus.org.uk%2Flcd%2F1ac688bb-eeef-4273-9e3e-b5c8e8a4a3b7%2F ('Cover (Library of Congress, 1466_027)') is of type with URI http://w3id.org/lob/concept/1268 whereas it should be with URI https://w3id.org/loc-vocab/F11b77275-d0a0-4790-ac52-ec10fa7736bb

P.S. Not sure this applies to SUL data as I have not been able to query them yet because of issue #7

**Comment by acampagnolo** [comment]
Fixed, but the new terms need to be remapped to SKOS for the vocabularies: https://docs.google.com/spreadsheets/d/1Os3vK-XwsqAaecIAoi3oTHi0V1PmTvUsevLichIfW40/edit?usp=sharing

**Comment by ryunleeuu** [comment]
Can you let me know if this applies to sul data now that #7 is closed? The one data point where I know this did occur was referring to items as type := "book" since I finessed the data to align it with the other datasets.
