### ISSUE TITLE
LC book labels and identifiers do not match

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#9]
The `rdfs:label` and the `P1_is_identified_by` properties for the books in the LC dataset do not match. For example:

label: "Book (Library of Congress, 2247)" - en
is identified by: Project Number (Library of Congress, 2247)

I would expect them to be identical and something like:

Book (Library of Congress, 2247 (Book)

**Comment by acampagnolo** [comment]
Not all items in the LoC datasets have a shelfmark or other identifiers. The only persistent Identifier within the dataset is the Project Number, that's why it looks like that. I can change it to match the suggestion, but wouldn't we lose the fact that the ID is the Conservation Project Number?

**Comment by natuk** [comment]
I see what you mean. Maybe we can update the RS template to take the human label from rdfs:label only and ignore the P1 property. OK, let's leave the data as is, and this is now a templating issue.

**Comment by natuk** [comment]
This is sorted now as the RS team updated the templates to give priority to the `rdfs:label` as opposed to `P1_is_identified_by`.
